import Head from 'next/head';
// import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar';
import Home from '@/components/Home';
import About from '@/components/About';
import Tools from '@/components/Tools';
import Projects from '@/components/Projects';
import Contact from '@/components/Contact';
// const inter = Inter({ subsets: ['latin'] });
export default function App() {
  return (
    <>
      <Head>
        <title>Teodor Briceanu</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <NavBar />
        <Home />
        <About />
        <Tools />
        <Projects />
        <Contact />
      </main>
    </>
  );
}
